### ISSUE TITLE
Exception while invoking method "uploadIMG" TypeError: path must be a string. Recieved undefined

### ISSUE THREAD

**Issue by GAWKmdk** [strack/PacktMeteorRecipes#1]
Hi there,

I get "Exception while invoking method "uploadIMG" TypeError: path must be a string. Recieved undefined" when I attempt to copy a photo locally to the drag and drop area. No issue using browser photos -- only when it writes to the local ".images" folder. Think its' related to the Processing.env.PWD but I'm not an expert -- any suggestion to fix this bug ?

**Comment by strack** [comment]
Hi Matthew,

I tried to replicate this, but am having issues doing so. Can you send me steps, and if possible your code base (if it's modified even slightly)?   Also, are you on Mac or Windows?
Thx!

**Comment by strack** [comment]
Following up before I close this... Let me know on the above. Thx!

**Comment by GAWKmdk** [comment]
Hey sorry,

I'm on Windows

The piece of code im stuck on is this iFile bit which is in the /server file directory  of the drag-and-drop image sample for Meteor. I can't seem to find any documentation on what iFile is besides some outdated references from 2014 on iFrames and web API so I can't seem to reference how the path might be concatinated. 

Evidently in the client its' calling Meteor.call('uploadIMG') -- but it can't locate the .images directory we made to store the uploaded images locally. 

I've also tried setting the src to .images/ and ./ with no luck ... 

Any help? 

This is the line it was referencing. 

`Meteor.methods({
    
    //adds uri reference
    addURL : function (uri) {
        Images.insert({src:uri});
    },
    
    //uploads to .images folder in public
    uploadIMG: function (iFile) {
    iFile.save('/.images/', {});
    Images.insert({
      src: 'images/' + iFile.name });},
`

**Comment by strack** [comment]
so I think there's two issues at play here (I'd try them out but I'm not in current possession of a windows device):

1- the `.images/` folder needs to exist. I don't know the file structure on windows well enough to comment. I know that it's hidden on macs, and that meteor ignores it, but you have to physically create the folder.

2- I am unsure if the `Processing.env.PWD` works on Windows. It's a common thing on Linux/OS X, but I don't know about windows. you should `console.log` that and make sure a value exists.  Also, check out this conversation, as I think it's related:  [https://github.com/tomitrescak/meteor-uploads/issues/49](https://github.com/tomitrescak/meteor-uploads/issues/49)

iFile is just a reference name to the I/O functionality inside of Node. I got hung up on that as well, but the default Node libraries support the I/O  (file) operations, so just go with it. That is definitely not the issue.

Hope this helps. I'll close this issue. Please reopen/comment if the above 2 don't resolve.
